put dast condition

diff --git a/.github/workflows/sample.yaml b/.github/workflows/sample.yaml
--- a/.github/workflows/sample.yaml
+++ b/.github/workflows/sample.yaml
@@ -47,7 +47,9 @@ jobs:
           echo "DAST Security Testing"
           docker run -d -p 3000:3000 --name juiceshop bkimminich/juice-shop 
           juiceip=$(docker inspect -f "{{.NetworkSettings.Networks.bridge.IPAddress }}" juiceshop)
-          docker run -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://$juiceip:3000 
+          docker run -t --name dast ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://$juiceip:3000 
+          if [[ "$(docker logs dast &> dast.log; cat dast.log | grep "WARN-NEW: .*" | wc -l)" -gt 0 ]]; then echo "failed due to dast security 
+          issues"; exit 1; else echo "All Good to proceed"; exit 0; fi
 
       #- name: Deploy
       #  run: |
