sast check

diff --git a/.github/workflows/sample.yaml b/.github/workflows/sample.yaml
--- a/.github/workflows/sample.yaml
+++ b/.github/workflows/sample.yaml
@@ -10,21 +10,23 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-     # - name: Checkout Source Code
-     #   run: |
-     #     echo "clone vulnerable repository"
-     #     git clone https://github.com/juice-shop/juice-shop.git
+      - name: Checkout Source Code
+        run: |
+          echo "clone vulnerable repository"
+          git clone https://github.com/juice-shop/juice-shop.git
 
-     # - name: Build
-     #   run: |
-     #     echo "listing all directories and files"
-     #     cd ${{ github.workspace }}/juice-shop
-     #     npm install
+      - name: Build
+        run: |
+          echo "listing all directories and files"
+          cd ${{ github.workspace }}/juice-shop
+          npm install
 
       - name: SAST
         run: |
           echo "run SAST security checks"
           docker run -t --name sast -v ${{ github.workspace }}/juice-shop:/path checkmarx/kics:latest scan -p /path -o "/path/" || true
+          if [[ "$(docker logs sast &> sast.log;  cat sast.log | grep -o 'HIGH: [1-9]\d*'  | awk '{print $2;}')" -gt 0 ]]; then echo "failed due to sast security
+          issues"; exit 1; else echo "All Good to proceed"; exit 0; fi
 
 
      # - name: SCA
