sast check

diff --git a/.github/workflows/sample.yaml b/.github/workflows/sample.yaml
--- a/.github/workflows/sample.yaml
+++ b/.github/workflows/sample.yaml
@@ -21,10 +21,10 @@ jobs:
      #     cd ${{ github.workspace }}/juice-shop
      #     npm install
 
-     # - name: SAST
-     #   run: |
-     #     echo "run SAST security checks"
-     #     docker run -t -v ${{ github.workspace }}/juice-shop:/path checkmarx/kics:latest scan -p /path -o "/path/" || true
+      - name: SAST
+        run: |
+          echo "run SAST security checks"
+          docker run -t --name sast -v ${{ github.workspace }}/juice-shop:/path checkmarx/kics:latest scan -p /path -o "/path/" || true
 
 
      # - name: SCA
@@ -36,13 +36,13 @@ jobs:
      #     cd ${{ github.workspace }}/juice-shop
      #     docker run --name sca -e SNYK_TOKEN=$SNYK_TOKEN -v ./:/app snyk/snyk:node || true
 
-      - name: Docker Container Security Test 
-        run: |
-          echo "Security Testing Container"
-          docker pull bkimminich/juice-shop
-          docker run --name containersecurity -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image bkimminich/juice-shop || true
-          if [[ "$(docker logs containersecurity &> containersecurity.log;  cat containersecurity.log | grep -o 'CRITICAL: [1-9]\d*'  | awk '{print $2;}')" -gt 0 ]]; then echo "failed due to container security
-          issues"; exit 1; else echo "All Good to proceed"; exit 0; fi
+     # - name: Docker Container Security Test 
+     #   run: |
+     #     echo "Security Testing Container"
+     #     docker pull bkimminich/juice-shop
+     #     docker run --name containersecurity -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image bkimminich/juice-shop || true
+     #     if [[ "$(docker logs containersecurity &> containersecurity.log;  cat containersecurity.log | grep -o 'CRITICAL: [1-9]\d*'  | awk '{print $2;}')" -gt 0 ]]; then echo "failed due to container security
+     #     issues"; exit 1; else echo "All Good to proceed"; exit 0; fi
 
      # - name: DAST
      #   run: |
