include sca check issues

diff --git a/.github/workflows/sample.yaml b/.github/workflows/sample.yaml
--- a/.github/workflows/sample.yaml
+++ b/.github/workflows/sample.yaml
@@ -21,22 +21,25 @@ jobs:
           cd ${{ github.workspace }}/juice-shop
           npm install
 
-      - name: SAST
-        run: |
-          echo "run SAST security checks"
-          docker run -t --name sast -v ${{ github.workspace }}/juice-shop:/path checkmarx/kics:latest scan -p /path -o "/path/" || true
-          if [[ "$(docker logs sast &> sast.log;  cat sast.log | grep 'HIGH' | tail -n 1 | awk '{print $2;}')" != 0 ]]; then echo "failed due to sast security
-          issues"; exit 1; else echo "All Good to proceed"; exit 0; fi
-
-
-     # - name: SCA
-     #   env:
-     #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+     # - name: SAST
      #   run: |
-     #     echo "run SCA security checks"
-     #     #echo $SNYK_TOKEN
-     #     cd ${{ github.workspace }}/juice-shop
-     #     docker run --name sca -e SNYK_TOKEN=$SNYK_TOKEN -v ./:/app snyk/snyk:node || true
+     #     echo "run SAST security checks"
+     #     docker run -t --name sast -v ${{ github.workspace }}/juice-shop:/path checkmarx/kics:latest scan -p /path -o "/path/" || true
+     #     if [[ "$(docker logs sast &> sast.log;  cat sast.log | grep 'HIGH' | tail -n 1 | awk '{print $2;}')" != 0 ]]; then echo "failed due to sast security
+     #     issues"; exit 1; else echo "All Good to proceed"; exit 0; fi
+
+
+      - name: SCA
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        run: |
+          echo "run SCA security checks"
+          #echo $SNYK_TOKEN
+          cd ${{ github.workspace }}/juice-shop
+          docker run --name sca -e SNYK_TOKEN=$SNYK_TOKEN -v ./:/app snyk/snyk:node || true
+         if [[ "$(docker logs sca &> sca.log; cat sca.log | grep -o 'found [1-9]\d* issues' | awk '{print $2;}')" -gt 0 ]]; then echo "failed due to sca security
+         issues"; exit 1; else echo "All Good to proceed"; exit 0; fi
+
 
      # - name: Docker Container Security Test 
      #   run: |
